### ISSUE TITLE
Hand object annotations?

### ISSUE THREAD

**Issue by jperezrua** [dfouhey/VLOGToolkit#1]
Hi,

Thanks a lot for the effort put in this repo!
I was wondering where can I get the hand annotations? I downloaded the xompressed files from the Google Drive but I can't seem to find it. 

Thanks again!

Juan

**Comment by dfouhey** [comment]
We released the labeled data and youtube ids here: http://web.eecs.umich.edu/~fouhey/2017/VLOG/data/data_v1.1.tgz in addition to videos (which I presume is the thing you downloaded)

**Comment by jperezrua** [comment]
thanks, you are right!
