### ISSUE TITLE
wrong total number about clip

### ISSUE THREAD

**Issue by JackSparrow3** [dfouhey/VLOGToolkit#2]
hi, 
thanks for the job! 
I download the dataset from google drive, and when i unzip the block_0.tar~block4.tar, i find it only contain 24888 clips. Since the paper said the total number is 114k, is there any way i can get the rest the clips?

**Comment by dfouhey** [comment]
Try untarring them one by one (i.e.
 tar xvf block0.tar 
tar xvf block1.tar 
tar xvf block2.tar ...). If you concatenate them, tar may only untar the first one.

**Comment by dfouhey** [comment]
Closing assuming the above fixes the issue. If not please reopen.
