### ISSUE TITLE
Some videos are unreachable in VLOG dataset

### ISSUE THREAD

**Issue by Jimmy880** [dfouhey/VLOGToolkit#3]
Hello
Thank you for providing this valuable dataset.
I download dataset according to the "youtube_links.txt" file using youtube_dl python package. I notice there are over 100K youtube url in the link file but I only get around 10K videos from it. Most of the videos are change to private in youtube, which make it unreachable for me.
I wonder whether there are other ways to download the full dataset?

**Comment by Jimmy880** [comment]
Sorry, I just find the google drive link in the dataset homepage. I guess I can get the whole dataset in it.
However, I am not very sure about the difference between the files named "block_*.tar" and "full_256_**.tar". Do you have the README file for the google drive?

**Comment by dfouhey** [comment]
There are only 16961 unique long videos in the dataset, which in turn produce ~113K clips consisting of a single shot. 

Sorry -- originally it was just the clips in the drive, so there was no readme, but I added more data.

block_0*tar is what you want -- the clips
full_256_*tar is the raw underlying videos resized to 256x256
framecache.tgz are the frames that have been annotated with contact state.
audio.tgz is audio for the videos

Hope that helps!

**Comment by Jimmy880** [comment]
Thank you for your reply. It is very useful!!
